Content:
    air:
        root_dir: doc/content
    framework:
        root_dir: ${MOOSE_DIR}/framework/doc/content
    fluid_properties:
        root_dir: ${MOOSE_DIR}/modules/fluid_properties/doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer

Extensions:
    MooseDocs.extensions.navigation:
        name: air
        repo: https://hpcgitlab.hpc.inl.gov/idaholab/air
        home: https://hpcsc.inl.gov/ssl/AIR/site/index.html
        menu:
            Developers:
                Workflow: workflow.md
                Build Status: https://moosebuild.inl.gov/repo/idaholab/air/

    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        includes:
            - include
            - ${MOOSE_DIR}/framework/include
            - ${MOOSE_DIR}/modules/fluid_properties/include
        remove:
            framework: !include ${MOOSE_DIR}/framework/doc/remove.yml

    MooseDocs.extensions.common:
        shortcuts:
            framework: !include ${MOOSE_DIR}/framework/doc/globals.yml

    MooseDocs.extensions.acronym:
        acronyms: !include ${MOOSE_DIR}/framework/doc/acronyms.yml
